# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Jenkins plugin with Maven

on:
  workflow_call:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: maven-settings-xml-action
      uses: whelk-io/maven-settings-xml-action@v22
      with:
        repositories: >
          [
            {
              "id": "repo.jenkins-ci.org",
              "url": "https://repo.jenkins-ci.org/public/"
            }
          ]
        plugin_repositories: >
          [
            {
              "id": "repo.jenkins-ci.org",
              "url": "https://repo.jenkins-ci.org/public/"
            }
          ]
        mirrors: >
          [
            {
              "id": "repo.jenkins-ci.org",
              "mirrorOf": "m.g.o-public",
              "url": "https://repo.jenkins-ci.org/public/"
            }
          ]
        plugin_groups: >
          [
            "org.jenkins-ci.tools"
          ]
        # output_file: .m2/settings.xml
    - name: Check mvn setting
      run: cat ~/.m2/settings.xml
    - name: Set mvnw executable
      run: chmod +x mvnw
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@v4.0.2
